### ISSUE TITLE
Related works

### ISSUE THREAD

**Issue by vaseline555** [huangtiansheng/fedslr#1]
Hi, I have run into this and found your work interesting!  
BTW, I am curious on some missing citations (or baseline comparison) in your work, e.g. *FedPara* (ICLR 2021; which uses low rank decomposition for communication efficiency), *FedRep* (ICML 2021; which uses partial model exchange for updating global knowledge while maintaining local part intact), *SuPerFed* (KDD 2022; which mixes local and global knowledge like *APFL* but explictly induces mode connectivity, and is currently SOTA in [PFL](https://paperswithcode.com/task/personalized-federated-learning))  
Is there any reason to exclude these works?

**Comment by huangtiansheng** [comment]
Apology for our delay response! 

We did try  implementing FedPara and FedRep, but the results are not satisfactory (potentially due to implementation issues, which might be misleading). Therefore we did  not release the code of these two baselines.  

For SuPerFed, we did not cite and compare because it is relatively new when FedSLR is published. I would try implementing it if I have time. Thank you for bring this issue to us!

**Comment by huangtiansheng** [comment]
> Hi, I have run into this and found your work interesting! BTW, I am curious on some missing citations (or baseline comparison) in your work, e.g. _FedPara_ (ICLR 2021; which uses low rank decomposition for communication efficiency), _FedRep_ (ICML 2021; which uses partial model exchange for updating global knowledge while maintaining local part intact), _SuPerFed_ (KDD 2022; which mixes local and global knowledge like _APFL_ but explictly induces mode connectivity, and is currently SOTA in [PFL](https://paperswithcode.com/task/personalized-federated-learning)) Is there any reason to exclude these works?

**Comment by vaseline555** [comment]
Nice. Thank you and hope you have a great day!
